Repository endoflife-date/release-data, pull requests merged in 2023-08, with the labels that each got.

#134 Update ruby dependencies
  Gemfile.lock
Labels: dependencies, ruby

#128 [splunk] add automation
  src/splunk.py
Labels: enhancement

#140 [apple] Fix slight html change
  src/apple.py
Labels: bug
