Repository endoflife-date/release-data, pull requests merged in 2023-11, with the labels that each got.

#171 Drop Ruby dockerhub auto method code
  update.rb
Labels: chore

#178 [git] Migrate git method from Ruby to Python
  releases/angular-js.json
  releases/oraclelinux.json
  requirements.txt
  src/common/git.py
  src/debian.py
  src/git.py
  update.rb
Labels: enhancement

#166 [aws-lambda] Add automation
  src/aws-lambda.py
  src/common/endoflife.py
Labels: enhancement

#184 Support parallel URL fetching via endoflife.fetch_urls
  src/common/endoflife.py
  src/cos.py
  src/firefox.py
Labels: enhancement

#188 Try to fix fetch_urls when ChunkedEncodingError occurs
  src/common/endoflife.py
Labels: bug

#187 [cos] Make HTTP requests in parallel
  src/cos.py
Labels: enhancement

#192 [haproxy] Make HTTP requests in parallel
  src/haproxy.py
Labels: enhancement

#191 [couchbase] Make HTTP requests in parallel
  src/couchbase-server.py
Labels: enhancement

#193 [splunk] Make HTTP requests in parallel
  src/splunk.py
Labels: enhancement

#194 Improve retry mechanism
  src/common/endoflife.py
  src/unity.py
Labels: bug

#172 [coldfusion] Adds coldfusion release automation
  src/coldfusion.py
  src/common/dates.py
Labels: enhancement
